### ISSUE TITLE
Cannot read property 'getQueryInterface' of undefined

### ISSUE THREAD

**Issue by pronitdas** [spinlud/sequelize-typescript-generator#10]
ts-node version 8.3.0
typescript version 3.8.3
node nersion 14.4.0
sequelize version 6.2.4
sequelize-typescript version 1.1.0

`/home/pronit/.nvm/versions/node/v14.3.0/lib/node_modules/sequelize/lib/model.js:55
    return this.sequelize.getQueryInterface();
                          ^

TypeError: Cannot read property 'getQueryInterface' of undefined
    at Function.get queryInterface [as queryInterface] (/home/pronit/.nvm/versions/node/v14.3.0/lib/node_modules/sequelize/lib/model.js:55:27)
    at isFunctionMember (/home/pronit/.nvm/versions/node/v14.3.0/lib/node_modules/sequelize-typescript/dist/model/model/model.js:99:25)
    at /home/pronit/.nvm/versions/node/v14.3.0/lib/node_modules/sequelize-typescript/dist/model/model/model.js:96:5
    at Array.filter (<anonymous>)
    at Object.<anonymous> (/home/pronit/.nvm/versions/node/v14.3.0/lib/node_modules/sequelize-typescript/dist/model/model/model.js:95:6)
`

**Comment by spinlud** [comment]
Hi @pronitdas, at the moment only `sequelize 5.x.x` is supported. I am waiting for [sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript) to be fully compatible with `sequelize 6.x.x`, see https://github.com/RobinBuschmann/sequelize-typescript/issues/785. Once ready I will try to make this library compatible with version 6 as well.

**Comment by pronitdas** [comment]
https://github.com/RobinBuschmann/sequelize-typescript/pull/807

they did upgrade to v6.1.1. Let me know if i could help in upgrading.

**Comment by spinlud** [comment]
Thanks for the update, but I am afraid they are [still in beta](https://github.com/RobinBuschmann/sequelize-typescript/pull/807#issuecomment-657782878) for v6 compatibility. I'll wait a stable npm release before to start working on an upgrade

**Comment by robpearmain** [comment]
I have worked around this by changing my package.json entry to:

"sequelize": "5.22.3",

Then nom install

**Comment by spinlud** [comment]
Sequelize v6.3.5 supported now.
