### ISSUE TITLE
How to convert the comment field to Chinese if the comment field is Unicode

### ISSUE THREAD

**Issue by qiufeihai** [spinlud/sequelize-typescript-generator#16]
How to convert the comment field to Chinese if the comment field is Unicode

comment: "\u521B\u5EFA\u65F6\u95F4"

**Comment by spinlud** [comment]
Hi! Please can you share dialect (Postgres, MySQL, etc), database version and CREATE TABLE statement for your table?

**Comment by jsicu** [comment]
> Hi! Please can you share dialect (Postgres, MySQL, etc), database version and CREATE TABLE statement for your table?

## Local usage example:

`npx stg -D mysql -h localhost -p 3306 -d koa2_server -u root -x password --indices --case camel --out-dir ./models --clean `

## CREATE TABLE statement：

`/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 80019
 Source Host           : localhost:3306
 Source Schema         : koa2_server

 Target Server Type    : MySQL
 Target Server Version : 80019
 File Encoding         : 65001

 Date: 14/05/2021 16:53:14
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for log
-- ----------------------------
DROP TABLE IF EXISTS `log`;
CREATE TABLE `log`  (
  `id` int(0) NOT NULL AUTO_INCREMENT,
  `type` int(0) NOT NULL COMMENT '日志类型',
  `ip` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '访问地址',
  `user_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '用户id',
  `method` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '请求方法',
  `original_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '请求接口',
  `token` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'token',
  `point` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '坐标',
  `address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '所在地',
  `update_time` datetime(6) NOT NULL DEFAULT '0162-09-12 09:32:46.000000' ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '最后更新时间',
  `delete_time` datetime(6) NULL DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of log
-- ----------------------------

SET FOREIGN_KEY_CHECKS = 1;
`
## model

`
import { Model, Table, Column, DataType, Index, Sequelize, ForeignKey } from 'sequelize-typescript';

interface logAttributes {
  id?: number;
  type: number;
  ip: string;
  userId?: string;
  method?: string;
  originalUrl?: string;
  token: string;
  point?: string;
  address?: string;
  updateTime: Date;
  deleteTime?: Date;
}

@Table({ tableName: 'log', timestamps: false })
export class log extends Model<logAttributes, logAttributes> implements logAttributes {
  @Column({ primaryKey: true, autoIncrement: true, type: DataType.INTEGER })
  @Index({ name: 'PRIMARY', using: 'BTREE', order: 'ASC', unique: true })
  id?: number;

  @Column({ type: DataType.INTEGER, comment: '\u65E5\u5FD7\u7C7B\u578B' })
  type!: number;

  @Column({ type: DataType.STRING(255), comment: '\u8BBF\u95EE\u5730\u5740' })
  ip!: string;

  @Column({ field: 'user_id', allowNull: true, type: DataType.STRING(255), comment: '\u7528\u6237id' })
  userId?: string;

  @Column({ allowNull: true, type: DataType.STRING(10), comment: '\u8BF7\u6C42\u65B9\u6CD5' })
  method?: string;

  @Column({ field: 'original_url', allowNull: true, type: DataType.STRING(255), comment: '\u8BF7\u6C42\u63A5\u53E3' })
  originalUrl?: string;

  @Column({ type: DataType.STRING(500), comment: 'token' })
  token!: string;

  @Column({ allowNull: true, type: DataType.STRING(50), comment: '\u5750\u6807' })
  point?: string;

  @Column({ allowNull: true, type: DataType.STRING(50), comment: '\u6240\u5728\u5730' })
  address?: string;

  @Column({ field: 'update_time', type: DataType.DATE(6), comment: '\u6700\u540E\u66F4\u65B0\u65F6\u95F4' })
  updateTime!: Date;

  @Column({ field: 'delete_time', allowNull: true, type: DataType.DATE(6), comment: '\u5220\u9664\u65F6\u95F4' })
  deleteTime?: Date;
}
`

I want to make the comment name in normal character than the Unicode code.

Thank you!

**Comment by spinlud** [comment]
Hi!
Should be fixed in `v8.1.1`
