### ISSUE TITLE
circular references

### ISSUE THREAD

**Issue by EDsish** [spinlud/sequelize-typescript-generator#17]
I have class A which has many of B
And then B belongs to A
When I try to add these generated model in to the sequelize models when it wants to add A it is missing B and when it trie to add B it is missing A, that's why I get This:
Foreign key for "XmlTemplate" is missing on "XmlExport". when 
```
@Table({ tableName: "XMLExport", timestamps: false})
export class XmlExport extends Model<XmlExport> {
    @Column({ primaryKey: true, autoIncrement: true, type: DataType.INTEGER })
    Id?: number;
    @BelongsTo(() => XmlTemplate)
    XmlTemplate?: XmlTemplate;   
}
```
and 
```
@Table({ tableName: "XMLTemplate", timestamps: false })
export class XmlTemplate extends Model<XmlTemplate> {
    @Column({ primaryKey: true, autoIncrement: true, type: DataType.INTEGER })
    Id?: number;
    @HasMany(() => XmlExport, { sourceKey: "Id" })
    XmlExports?: XmlExport[];
}
```
I add models like this
```
sequelize.addModels([
,XmlExport
,XmlTemplate]);
```

**Comment by spinlud** [comment]
Hi, I am not sure what is the issue you are facing. Could you share the Dialect (MySQL, Postgres), database version and SQL create table statements for the tables?
