### ISSUE TITLE
How migrations work?

### ISSUE THREAD

**Issue by icecreamsandwich** [spinlud/sequelize-typescript-generator#20]
In the sequelize-cli tool There is migrations and seeders will be created automatically when doing the model generate command (For eg: `npx sequelize-cli model:generate --name User --attributes firstName:string`). and then we can run `npx sequelize-cli db:migrate`. 

Do we have the migrations created here when we run `stg -D mysql -h localhost -p 3306 -d myDatabase -u myUsername -x myPassword --indices --case camel --out-dir models --clean` OR do we have to create the migrations manually?

**Comment by spinlud** [comment]
Hi!
Migrations are not supported at the moment, but PRs on the matter are welcome 😁

**Comment by icecreamsandwich** [comment]
Thanks. Will look in to that.
