### ISSUE TITLE
Can I generate with unicode field name?

### ISSUE THREAD

**Issue by leduclinh7141** [spinlud/sequelize-typescript-generator#6]
Thank you for your great tool. 
I run in trouble with a table with the field name in Unicode (Japanese).
When I use the underscore config:
metadata: {
            indices: true,
            case: 'UNDERSCORE',
        },

the generated column like that:

 @Column({ field: "\u53D6\u5F15\u5148", allowNull: true, type: DataType.STRING(-1) })
    ?: string;
I want to make the field name in normal character than the Unicode code.

Thank you!

**Comment by spinlud** [comment]
Hi, thanks for the feedback!

Could you provide the following:
- Database type and version
- CREATE table statement to reproduce the issue

Cheers!

**Comment by leduclinh7141** [comment]
I am using mssql database SQL server express 2017.
Create table script like this:

USE [CODEDB]
GO

/****** Object:  Table [dbo].[機種]    Script Date: 2020/04/16 8:25:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[機種](
	[ID] [int] NOT NULL,
	[ｺｰﾄﾞ] [int] NULL,
	[機種] [nvarchar](255) NULL,
) ON [PRIMARY]

GO
 Thank you!

**Comment by leduclinh7141** [comment]
this is the code for generator:

(async () => {
    const config: IConfig = {
        connection: {
            dialect: 'mssql',
            host: 'localhost',
            port: 64034,
            database: 'CODEDB',
            username: '*',
            password: '*'
        },
        metadata: {
            indices: true,
            case: 'UNDERSCORE',
        },
        output: {
            clean: true,
            outDir: 'models'
        }
    };
 
    const dialect = new DialectMSSQL();
 
    const builder = new ModelBuilder(config, dialect);
 
    try {
        await builder.build();
    }
    catch(err) {
        console.error(err);
        process.exit(1);
    }    
})();

Without the **case: 'UNDERSCORE',**. I work well.

**Comment by spinlud** [comment]
Thanks! I am bit busy these days but I will look into that as soon as i can

**Comment by spinlud** [comment]
Hi, unfortunately it seems that the library which I am using for case transforming does not handle correctly non ASCII characters (at least for japanese words) [change-case](https://www.npmjs.com/package/change-case). 
In `v2.3.0` I've added default unicode strings support for MSSQL and any transformation for non ASCII characters will be skipped (a warning will be printed instead). This is also stated in the documentation. 
I will let you know if I can find a better solution.

**Comment by lawrence-peng** [comment]
try do :
  ``` generatedCode = unescape(generatedCode.replace(/\\u/g, "%u"));```
